### PR TITLE
feat: update image tag values

### PR DESCRIPTION
**Pull request by AhmedMItman**

### CODE REVIEW

**Review by shawara — COMMENTED** [review]
@AhmedMItman 
I think we shouldn't do this change in the plugin to keep it separated from this logic in case someone wants to use it and doesn't have the values-gke.yml it will be a problem.

So, in my opinion, I think it would be better to make a small change in the deployment template will do the same result
for example this https://github.com/swvl/api/blob/master/chart/api/templates/server-deployment.yaml#L80
should be changed as below
```yaml
image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
```
then in your `values-gke.yaml` comment the tag

**Comment by shawara** [comment]
@AhmedMItman 
There is another way you can set tag in `values-gke.yaml` file
```yaml
image:
  tag: "v{{.Chart.AppVersion}}"
```

and in the `templates/deployment.yaml` file set image
```yaml
image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
```

**Comment by AhmedFat7y** [comment]
@AhmedMItman is this PR tested bro?

**Comment by AhmedFat7y** [comment]
@AhmedMItman I opened another PR with the same changes and fixed couple of things https://github.com/swvl/semantic-release-helm/pull/16

**Pull request closed without merging**
